/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mediumapi.apiclient;

import com.mediumapi.client.WelcomeApiClient;
import com.mediumapi.domain.welcome.Get200Response;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

public interface WelcomeApi {

  default WelcomeApiClient getDelegate() {
    return new WelcomeApiClient() {
    };
  }

  /**
   * GET / : Get Welcome **Test Endpoint** Returns the information about the
   * Unofficial Medium API
   *
   * @return OK (status code 200)
   */
  @Operation(operationId = "rootGet", summary = "Get Welcome", description = "**Test Endpoint** Returns the information about the Unofficial Medium API ", tags = {
      "Welcome"}, responses = {@ApiResponse(responseCode = "200", description = "OK", content = {
          @Content(mediaType = "application/json", schema = @Schema(implementation = Get200Response.class))})})
  @RequestMapping(method = RequestMethod.GET, value = "/", produces = {"application/json"})

  default ResponseEntity<Get200Response> rootGet(

  ) {
    return getDelegate().rootGet();
  }

}
